idf_component_register(
    SRCS
        "main.c"
        "modbus_handler.c"
        "serial_handler.c"
        "can_handler.c"
        "adc_handler.c"
        "ble_scanner.c"
        "net_handler.c"
        "dio_handler.c"
        "max14906.c"
        "iout_handler.c"
        "safety.c"
        "log.c"
    INCLUDE_DIRS
        "."
        "../include"
    REQUIRES
        driver
        esp_timer
        esp_adc
        esp_eth
        esp_netif
        esp_event
        lwip
        json
        spi_flash
        usb
        esp_system
        bt
        nvs_flash
)
